# Site settings
title: "Igor Shalyminov"
description: "Igor Shalyminov | Speech and Dialogue Research"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Igor Shalyminov"
resume_title:                   "Speech and Dialogue Research"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "igor@shalyminov.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+447308130798"
resume_contact_address:         "Amazon R&D, Aureliusstraße 2, Aachen, 52064, Germany"

resume_header_contact_info:     "Amazon R&D, Aureliusstraße 2, Aachen, 52064, Germany<br/>+447308130798 • igor@shalyminov.com"
display_header_contact_info:    "true"

resume_header_intro: I'm a PhD graduate from the <a href="https://sites.google.com/site/hwinteractionlab/">Interaction Lab, Heriot-Watt University</a> (Edinburgh, UK) working on Machine Learning/Natural Language Processing methods for data-efficient, robust, and practically applicable dialogue systems. If you think my background could be useful for you, please feel free to

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_links:           true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
resume_section_recognition:     true
resume_section_experience:      true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ishalyminov"
  resume_twitter_url:           "http://twitter.com/pure_virtual"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://fb.com/igor.shalyminov"
  resume_linkedin_url:          "https://www.linkedin.com/in/ishalyminov"
  resume_instagram_url:         "https://instagram.com/pure_virtual"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
